### ISSUE TITLE
cant upload code 

### ISSUE THREAD

**Issue by TrHbAO** [nopnop2002/Arduino-STM32-Ethernet-LAN8720#11]
hi, i got this problem when trying to upload the code using the example "WebServer" of STM32Ethernet library? please help me...

c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:80:15: error: 'ETH_DMADescTypeDef' does not name a type; did you mean 'RTC_DateTypeDef'?
   80 | __ALIGN_BEGIN ETH_DMADescTypeDef  DMARxDscrTab[ETH_RXBUFNB] __ALIGN_END;/* Ethernet Rx MA Descriptor */
      |               ^~~~~~~~~~~~~~~~~~
      |               RTC_DateTypeDef
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:85:15: error: 'ETH_DMADescTypeDef' does not name a type; did you mean 'RTC_DateTypeDef'?
   85 | __ALIGN_BEGIN ETH_DMADescTypeDef  DMATxDscrTab[ETH_TXBUFNB] __ALIGN_END;/* Ethernet Tx DMA Descriptor */
      |               ^~~~~~~~~~~~~~~~~~
      |               RTC_DateTypeDef
In file included from C:\Users\cobra\AppData\Local\Arduino15\packages\STMicroelectronics\hardware\stm32\2.7.1\system/STM32F4xx/stm32f4xx_hal_conf.h:13,
                 from C:\Users\cobra\AppData\Local\Arduino15\packages\STMicroelectronics\hardware\stm32\2.7.1\system/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal.h:29,
                 from C:\Users\cobra\AppData\Local\Arduino15\packages\STMicroelectronics\hardware\stm32\2.7.1\system/Drivers/CMSIS/Device/ST/STM32F4xx/Include/stm32f4xx.h:287,
                 from C:\Users\cobra\AppData\Local\Arduino15\packages\STMicroelectronics\hardware\stm32\2.7.1\cores\arduino/stm32/stm32_def.h:36,
                 from c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:48:
C:\Users\cobra\AppData\Local\Arduino15\packages\STMicroelectronics\hardware\stm32\2.7.1\system/STM32F4xx/stm32f4xx_hal_conf_default.h:308:40: error: 'ETH_MAX_PACKET_SIZE' was not declared in this scope
  308 | #define ETH_RX_BUF_SIZE                ETH_MAX_PACKET_SIZE /* buffer size for receive               */
      |                                        ^~~~~~~~~~~~~~~~~~~
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:90:44: note: in expansion of macro 'ETH_RX_BUF_SIZE'
   90 | __ALIGN_BEGIN uint8_t Rx_Buff[ETH_RXBUFNB][ETH_RX_BUF_SIZE] __ALIGN_END; /* Ethernet Receive Buffer */
      |                                            ^~~~~~~~~~~~~~~
C:\Users\cobra\AppData\Local\Arduino15\packages\STMicroelectronics\hardware\stm32\2.7.1\system/STM32F4xx/stm32f4xx_hal_conf_default.h:309:40: error: 'ETH_MAX_PACKET_SIZE' was not declared in this scope
  309 | #define ETH_TX_BUF_SIZE                ETH_MAX_PACKET_SIZE /* buffer size for transmit              */
      |                                        ^~~~~~~~~~~~~~~~~~~
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:95:44: note: in expansion of macro 'ETH_TX_BUF_SIZE'
   95 | __ALIGN_BEGIN uint8_t Tx_Buff[ETH_TXBUFNB][ETH_TX_BUF_SIZE] __ALIGN_END; /* Ethernet Transmit Buffer */
      |                                            ^~~~~~~~~~~~~~~
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:97:8: error: 'ETH_HandleTypeDef' does not name a type; did you mean 'RTC_HandleTypeDef'?
   97 | static ETH_HandleTypeDef EthHandle;
      |        ^~~~~~~~~~~~~~~~~
      |        RTC_HandleTypeDef
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:116:6: error: variable or field 'HAL_ETH_MspInit' declared void
  116 | void HAL_ETH_MspInit(ETH_HandleTypeDef *heth)
      |      ^~~~~~~~~~~~~~~
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:116:22: error: 'ETH_HandleTypeDef' was not declared in this scope; did you mean 'RTC_HandleTypeDef'?
  116 | void HAL_ETH_MspInit(ETH_HandleTypeDef *heth)
      |                      ^~~~~~~~~~~~~~~~~
      |                      RTC_HandleTypeDef
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:116:41: error: 'heth' was not declared in this scope
  116 | void HAL_ETH_MspInit(ETH_HandleTypeDef *heth)
      |                                         ^~~~
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp: In function 'void low_level_init(netif*)':
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:168:3: error: 'EthHandle' was not declared in this scope
  168 |   EthHandle.Instance = ETH;
      |   ^~~~~~~~~
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:170:36: error: 'ETH_AUTONEGOTIATION_ENABLE' was not declared in this scope
  170 |   EthHandle.Init.AutoNegotiation = ETH_AUTONEGOTIATION_ENABLE;
      |                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:171:26: error: 'ETH_SPEED_100M' was not declared in this scope
  171 |   EthHandle.Init.Speed = ETH_SPEED_100M;
      |                          ^~~~~~~~~~~~~~
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:172:31: error: 'ETH_MODE_FULLDUPLEX' was not declared in this scope
  172 |   EthHandle.Init.DuplexMode = ETH_MODE_FULLDUPLEX;
      |                               ^~~~~~~~~~~~~~~~~~~
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:174:35: error: 'ETH_MEDIA_INTERFACE_RMII' was not declared in this scope
  174 |   EthHandle.Init.MediaInterface = ETH_MEDIA_INTERFACE_RMII;
      |                                   ^~~~~~~~~~~~~~~~~~~~~~~~
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:181:27: error: 'ETH_RXPOLLING_MODE' was not declared in this scope
  181 |   EthHandle.Init.RxMode = ETH_RXPOLLING_MODE;
      |                           ^~~~~~~~~~~~~~~~~~
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:183:33: error: 'ETH_CHECKSUM_BY_HARDWARE' was not declared in this scope; did you mean 'CHECKSUM_BY_HARDWARE'?
  183 |   EthHandle.Init.ChecksumMode = ETH_CHECKSUM_BY_HARDWARE;
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~
      |                                 CHECKSUM_BY_HARDWARE
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:187:7: error: 'HAL_ETH_Init' was not declared in this scope; did you mean 'HAL_RTC_Init'?
  187 |   if (HAL_ETH_Init(&EthHandle) == HAL_OK) {
      |       ^~~~~~~~~~~~
      |       HAL_RTC_Init
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:193:41: error: 'DMATxDscrTab' was not declared in this scope
  193 |   HAL_ETH_DMATxDescListInit(&EthHandle, DMATxDscrTab, &Tx_Buff[0][0], ETH_TXBUFNB);
      |                                         ^~~~~~~~~~~~
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:193:56: error: 'Tx_Buff' was not declared in this scope
  193 |   HAL_ETH_DMATxDescListInit(&EthHandle, DMATxDscrTab, &Tx_Buff[0][0], ETH_TXBUFNB);
      |                                                        ^~~~~~~
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:193:3: error: 'HAL_ETH_DMATxDescListInit' was not declared in this scope
  193 |   HAL_ETH_DMATxDescListInit(&EthHandle, DMATxDscrTab, &Tx_Buff[0][0], ETH_TXBUFNB);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:196:41: error: 'DMARxDscrTab' was not declared in this scope
  196 |   HAL_ETH_DMARxDescListInit(&EthHandle, DMARxDscrTab, &Rx_Buff[0][0], ETH_RXBUFNB);
      |                                         ^~~~~~~~~~~~
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:196:56: error: 'Rx_Buff' was not declared in this scope
  196 |   HAL_ETH_DMARxDescListInit(&EthHandle, DMARxDscrTab, &Rx_Buff[0][0], ETH_RXBUFNB);
      |                                                        ^~~~~~~
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:196:3: error: 'HAL_ETH_DMARxDescListInit' was not declared in this scope
  196 |   HAL_ETH_DMARxDescListInit(&EthHandle, DMARxDscrTab, &Rx_Buff[0][0], ETH_RXBUFNB);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:217:3: error: 'HAL_ETH_Start' was not declared in this scope; did you mean 'HAL_DMA_Start'?
  217 |   HAL_ETH_Start(&EthHandle);
      |   ^~~~~~~~~~~~~
      |   HAL_DMA_Start
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:223:3: error: 'HAL_ETH_ReadPHYRegister' was not declared in this scope
  223 |   HAL_ETH_ReadPHYRegister(&EthHandle, PHY_IMR, &regvalue);
      |   ^~~~~~~~~~~~~~~~~~~~~~~
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:228:3: error: 'HAL_ETH_WritePHYRegister' was not declared in this scope
  228 |   HAL_ETH_WritePHYRegister(&EthHandle, PHY_IMR, regvalue);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp: In function 'err_t low_level_output(netif*, pbuf*)':
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:254:33: error: 'EthHandle' was not declared in this scope
  254 |   uint8_t *buffer = (uint8_t *)(EthHandle.TxDesc->Buffer1Addr);
      |                                 ^~~~~~~~~
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:255:8: error: 'ETH_DMADescTypeDef' does not name a type; did you mean 'RTC_DateTypeDef'?
  255 |   __IO ETH_DMADescTypeDef *DmaTxDesc;
      |        ^~~~~~~~~~~~~~~~~~
      |        RTC_DateTypeDef
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:263:3: error: 'DmaTxDesc' was not declared in this scope
  263 |   DmaTxDesc = EthHandle.TxDesc;
      |   ^~~~~~~~~
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:269:30: error: 'ETH_DMATXDESC_OWN' was not declared in this scope
  269 |     if ((DmaTxDesc->Status & ETH_DMATXDESC_OWN) != (uint32_t)RESET) {
      |                              ^~~~~~~~~~~~~~~~~
C:\Users\cobra\AppData\Local\Arduino15\packages\STMicroelectronics\hardware\stm32\2.7.1\system/STM32F4xx/stm32f4xx_hal_conf_default.h:309:40: error: 'ETH_MAX_PACKET_SIZE' was not declared in this scope
  309 | #define ETH_TX_BUF_SIZE                ETH_MAX_PACKET_SIZE /* buffer size for transmit              */
      |                                        ^~~~~~~~~~~~~~~~~~~
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:279:47: note: in expansion of macro 'ETH_TX_BUF_SIZE'
  279 |     while ((byteslefttocopy + bufferoffset) > ETH_TX_BUF_SIZE) {
      |                                               ^~~~~~~~~~~~~~~
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:284:20: error: 'ETH_DMADescTypeDef' was not declared in this scope; did you mean 'RTC_DateTypeDef'?
  284 |       DmaTxDesc = (ETH_DMADescTypeDef *)(DmaTxDesc->Buffer2NextDescAddr);
      |                    ^~~~~~~~~~~~~~~~~~
      |                    RTC_DateTypeDef
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:284:40: error: expected primary-expression before ')' token
  284 |       DmaTxDesc = (ETH_DMADescTypeDef *)(DmaTxDesc->Buffer2NextDescAddr);
      |                                        ^
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:287:32: error: 'ETH_DMATXDESC_OWN' was not declared in this scope
  287 |       if ((DmaTxDesc->Status & ETH_DMATXDESC_OWN) != (uint32_t)RESET) {
      |                                ^~~~~~~~~~~~~~~~~
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:307:3: error: 'HAL_ETH_TransmitFrame' was not declared in this scope
  307 |   HAL_ETH_TransmitFrame(&EthHandle, framelength);
      |   ^~~~~~~~~~~~~~~~~~~~~
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp: In function 'pbuf* low_level_input(netif*)':
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:338:8: error: 'ETH_DMADescTypeDef' does not name a type; did you mean 'RTC_DateTypeDef'?
  338 |   __IO ETH_DMADescTypeDef *dmarxdesc;
      |        ^~~~~~~~~~~~~~~~~~
      |        RTC_DateTypeDef
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:346:36: error: 'EthHandle' was not declared in this scope
  346 |   if (HAL_ETH_GetReceivedFrame_IT(&EthHandle) != HAL_OK) {
      |                                    ^~~~~~~~~
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:346:7: error: 'HAL_ETH_GetReceivedFrame_IT' was not declared in this scope
  346 |   if (HAL_ETH_GetReceivedFrame_IT(&EthHandle) != HAL_OK) {
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:351:9: error: 'EthHandle' was not declared in this scope
  351 |   len = EthHandle.RxFrameInfos.length;
      |         ^~~~~~~~~
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:360:5: error: 'dmarxdesc' was not declared in this scope
  360 |     dmarxdesc = EthHandle.RxFrameInfos.FSRxDesc;
      |     ^~~~~~~~~
C:\Users\cobra\AppData\Local\Arduino15\packages\STMicroelectronics\hardware\stm32\2.7.1\system/STM32F4xx/stm32f4xx_hal_conf_default.h:308:40: error: 'ETH_MAX_PACKET_SIZE' was not declared in this scope
  308 | #define ETH_RX_BUF_SIZE                ETH_MAX_PACKET_SIZE /* buffer size for receive               */
      |                                        ^~~~~~~~~~~~~~~~~~~
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:368:49: note: in expansion of macro 'ETH_RX_BUF_SIZE'
  368 |       while ((byteslefttocopy + bufferoffset) > ETH_RX_BUF_SIZE) {
      |                                                 ^~~~~~~~~~~~~~~
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:373:22: error: 'ETH_DMADescTypeDef' was not declared in this scope; did you mean 'RTC_DateTypeDef'?
  373 |         dmarxdesc = (ETH_DMADescTypeDef *)(dmarxdesc->Buffer2NextDescAddr);
      |                      ^~~~~~~~~~~~~~~~~~
      |                      RTC_DateTypeDef
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:373:42: error: expected primary-expression before ')' token
  373 |         dmarxdesc = (ETH_DMADescTypeDef *)(dmarxdesc->Buffer2NextDescAddr);
      |                                          ^
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:389:3: error: 'dmarxdesc' was not declared in this scope
  389 |   dmarxdesc = EthHandle.RxFrameInfos.FSRxDesc;
      |   ^~~~~~~~~
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:392:26: error: 'ETH_DMARXDESC_OWN' was not declared in this scope
  392 |     dmarxdesc->Status |= ETH_DMARXDESC_OWN;
      |                          ^~~~~~~~~~~~~~~~~
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:393:18: error: 'ETH_DMADescTypeDef' was not declared in this scope; did you mean 'RTC_DateTypeDef'?
  393 |     dmarxdesc = (ETH_DMADescTypeDef *)(dmarxdesc->Buffer2NextDescAddr);
      |                  ^~~~~~~~~~~~~~~~~~
      |                  RTC_DateTypeDef
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:393:38: error: expected primary-expression before ')' token
  393 |     dmarxdesc = (ETH_DMADescTypeDef *)(dmarxdesc->Buffer2NextDescAddr);
      |                                      ^
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp: In function 'uint8_t ethernetif_is_init()':
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:449:11: error: 'EthHandle' was not declared in this scope
  449 |   return (EthHandle.State != HAL_ETH_STATE_RESET);
      |           ^~~~~~~~~
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:449:30: error: 'HAL_ETH_STATE_RESET' was not declared in this scope; did you mean 'HAL_RTC_STATE_RESET'?
  449 |   return (EthHandle.State != HAL_ETH_STATE_RESET);
      |                              ^~~~~~~~~~~~~~~~~~~
      |                              HAL_RTC_STATE_RESET
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp: In function 'void ethernetif_set_link(netif*)':
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:509:28: error: 'EthHandle' was not declared in this scope
  509 |   HAL_ETH_ReadPHYRegister(&EthHandle, PHY_ISFR, &regvalue);
      |                            ^~~~~~~~~
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:509:3: error: 'HAL_ETH_ReadPHYRegister' was not declared in this scope
  509 |   HAL_ETH_ReadPHYRegister(&EthHandle, PHY_ISFR, &regvalue);
      |   ^~~~~~~~~~~~~~~~~~~~~~~
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp: In function 'void ethernetif_update_config(netif*)':
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:542:9: error: 'EthHandle' was not declared in this scope
  542 |     if (EthHandle.Init.AutoNegotiation != ETH_AUTONEGOTIATION_DISABLE) {
      |         ^~~~~~~~~
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:542:43: error: 'ETH_AUTONEGOTIATION_DISABLE' was not declared in this scope
  542 |     if (EthHandle.Init.AutoNegotiation != ETH_AUTONEGOTIATION_DISABLE) {
      |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:545:7: error: 'HAL_ETH_ReadPHYRegister' was not declared in this scope
  545 |       HAL_ETH_ReadPHYRegister(&EthHandle, PHY_SR, &regvalue);
      |       ^~~~~~~~~~~~~~~~~~~~~~~
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:553:37: error: 'ETH_MODE_FULLDUPLEX' was not declared in this scope
  553 |         EthHandle.Init.DuplexMode = ETH_MODE_FULLDUPLEX;
      |                                     ^~~~~~~~~~~~~~~~~~~
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:556:37: error: 'ETH_MODE_HALFDUPLEX' was not declared in this scope
  556 |         EthHandle.Init.DuplexMode = ETH_MODE_HALFDUPLEX;
      |                                     ^~~~~~~~~~~~~~~~~~~
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:561:32: error: 'ETH_SPEED_10M' was not declared in this scope
  561 |         EthHandle.Init.Speed = ETH_SPEED_10M;
      |                                ^~~~~~~~~~~~~
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:564:32: error: 'ETH_SPEED_100M' was not declared in this scope
  564 |         EthHandle.Init.Speed = ETH_SPEED_100M;
      |                                ^~~~~~~~~~~~~~
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:573:7: error: 'HAL_ETH_WritePHYRegister' was not declared in this scope
  573 |       HAL_ETH_WritePHYRegister(&EthHandle, PHY_BCR, ((uint16_t)(EthHandle.Init.DuplexMode >> 3) |
      |       ^~~~~~~~~~~~~~~~~~~~~~~~
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:578:24: error: 'EthHandle' was not declared in this scope
  578 |     HAL_ETH_ConfigMAC(&EthHandle, (ETH_MACInitTypeDef *) NULL);
      |                        ^~~~~~~~~
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:578:36: error: 'ETH_MACInitTypeDef' was not declared in this scope; did you mean 'TIM_OC_InitTypeDef'?
  578 |     HAL_ETH_ConfigMAC(&EthHandle, (ETH_MACInitTypeDef *) NULL);
      |                                    ^~~~~~~~~~~~~~~~~~
      |                                    TIM_OC_InitTypeDef
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:578:56: error: expected primary-expression before ')' token
  578 |     HAL_ETH_ConfigMAC(&EthHandle, (ETH_MACInitTypeDef *) NULL);
      |                                                        ^
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:578:5: error: 'HAL_ETH_ConfigMAC' was not declared in this scope
  578 |     HAL_ETH_ConfigMAC(&EthHandle, (ETH_MACInitTypeDef *) NULL);
      |     ^~~~~~~~~~~~~~~~~
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:581:5: error: 'HAL_ETH_Start' was not declared in this scope; did you mean 'HAL_DMA_Start'?
  581 |     HAL_ETH_Start(&EthHandle);
      |     ^~~~~~~~~~~~~
      |     HAL_DMA_Start
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:584:19: error: 'EthHandle' was not declared in this scope
  584 |     HAL_ETH_Stop(&EthHandle);
      |                   ^~~~~~~~~
c:\Users\cobra\OneDrive\Documents\Arduino\libraries\STM32duino_STM32Ethernet\src\utility\ethernetif.cpp:584:5: error: 'HAL_ETH_Stop' was not declared in this scope; did you mean 'HAL_DAC_Stop'?
  584 |     HAL_ETH_Stop(&EthHandle);
      |     ^~~~~~~~~~~~
      |     HAL_DAC_Stop

exit status 1

Compilation error: exit status 1

**Comment by nopnop2002** [comment]
This project cannot be built with core version 2.3 or higher.

**Comment by TrHbAO** [comment]
> This project cannot be built with core version 2.3 or higher.

well i just downgraded to 2.1.0 and still got the problem

**Comment by nopnop2002** [comment]
You have to modify your local file.
```
/* Section 2: PHY configuration section */
#if !defined  (LAN8742A_PHY_ADDRESS)
/* LAN8742A PHY Address*/
#define LAN8742A_PHY_ADDRESS            0x00U
#endif
```

**Comment by TrHbAO** [comment]
![Screenshot 2024-05-26 094014](https://github.com/nopnop2002/Arduino-STM32-Ethernet-LAN8720/assets/170788440/9ad8b092-8599-41d4-a5d6-dd4521602770)
i edited just like that and still got the problem...

**Comment by TrHbAO** [comment]
this is my setting 
![image](https://github.com/nopnop2002/Arduino-STM32-Ethernet-LAN8720/assets/170788440/c0dc7631-a16b-47b0-a9aa-03966f635647)
![Screenshot 2024-05-26 094448](https://github.com/nopnop2002/Arduino-STM32-Ethernet-LAN8720/assets/170788440/776118df-a580-4b26-bc6e-2800e87b847e)
![Screenshot 2024-05-26 094532](https://github.com/nopnop2002/Arduino-STM32-Ethernet-LAN8720/assets/170788440/399cf37f-d31f-4a5e-bc22-e17aa4872047)
![Screenshot 2024-05-26 094608](https://github.com/nopnop2002/Arduino-STM32-Ethernet-LAN8720/assets/170788440/057acb70-fa6f-4bb0-baaf-2c115eb66fdb)

**Comment by nopnop2002** [comment]
I'm using Arduino V1.


![ArduinoIDE_V1 8 19](https://github.com/nopnop2002/Arduino-STM32-Ethernet-LAN8720/assets/6020549/b0f512bd-b203-48b1-967c-2bc84738c6bd)

**Comment by TrHbAO** [comment]
the problem is solved after i change board part number to : Generic F407VETx
