### ISSUE TITLE
Support communication LAN8720

### ISSUE THREAD

**Issue by Ddh012345dhD** [nopnop2002/Arduino-STM32-Ethernet-LAN8720#7]
![image](https://user-images.githubusercontent.com/54657357/112928644-326f7880-9141-11eb-810f-d43cba00b80e.png)
How to fix this error?Help me!

**Comment by nopnop2002** [comment]
Did you install this ?

STM32 core support for Arduino.
https://github.com/stm32duino/Arduino_Core_STM32

Arduino library to support Ethernet for STM32 based board.
https://github.com/stm32duino/STM32Ethernet

Lightweight TCP/IP stack (LwIP) is a small independent implementation of the TCP/IP protocol suite.
https://github.com/stm32duino/LwIP

**Comment by Ddh012345dhD** [comment]
I installed all of them

**Comment by nopnop2002** [comment]
This is mine.

Are you the same?

![stm32](https://user-images.githubusercontent.com/6020549/113066971-72446780-91f6-11eb-836a-8db2cb868421.JPG)

FreeRTOS doesn't matter

![stm32-2](https://user-images.githubusercontent.com/6020549/113067429-4aa1cf00-91f7-11eb-9272-7620e44b1c4a.jpg)

**Comment by Ddh012345dhD** [comment]
![image](https://user-images.githubusercontent.com/54657357/113083724-e25ae980-9206-11eb-9b88-90c7f1a87529.png)
my library manager

**Comment by Ddh012345dhD** [comment]
![image](https://user-images.githubusercontent.com/54657357/113084293-e804ff00-9207-11eb-9898-3288ea3182dd.png)
error: 'ETH_DMADescTypeDef' does not name a type
error: 'ETH_DMADescTypeDef' does not name a type

**Comment by nopnop2002** [comment]
```
error: 'ETH_DMADescTypeDef' does not name a type
error: 'ETH_DMADescTypeDef' does not name a type
```


These are used inside the STM32duino library, not my sketches.

No problem in my environment

It may be affected by other libraries such as STM32duino_FreeRTOS.

Contact to ST-Micro.
