### ISSUE TITLE
hi,help.

### ISSUE THREAD

**Issue by ChinaBurn** [nopnop2002/Arduino-STM32-Ethernet-LAN8720#9]
Hi, I was wondering if there is a driver that supports LAN9303 on esp32

**Comment by nopnop2002** [comment]
I don’t use Arduino core for ESP32.

ESP-IDF supports wired LAN modules with MII or RMII interfaces.

A typical PHY is LAN8720.


LAN9303 is an MII interface.
So it can be used with the standard driver of ESP-IDF.
